### ISSUE TITLE
Support ignore hidden directories and files

### ISSUE THREAD

**Issue by dvdciri** [nspragg/filesniffer#15]
With the new api I can't use the FILE_HOUND criteria anymore and therefore can't use the 
.ignoreHiddenDirectories()
.ignoreHiddenFiles()
Would be good to add them to filesniffer

**Comment by dvdciri** [comment]
Same thing for the .ext('.ext1', '.ext2'); we can't specify the extension now, without file hound. Not sure if it can be done in a different way

**Comment by nspragg** [comment]
@dvdciri - you can use a combination of FileHound and the new `.paths` method. 

For example:
```js
const {FileSniffer, asArray} = require('filesniffer');
const FileHound = require('filehound');

async function main() {
  const files = await FileHound
    .create()
    .ext('.txt')
    .ignoreHiddenDirectories()
    .ignoreHiddenFiles()
    .find();
  
  const matches = await FileSniffer
    .create()
    .paths(files) // accepts files, directories or both
    .collect(asArray())
    .find(/someStr/i);

    console.log(matches);
}

main();
```

**Comment by dvdciri** [comment]
Cool, then maybe you can add that to the documentation so people know that file hound is still supported, in a way.
Thanks

**Comment by dvdciri** [comment]
On a side node, that would be less efficient as you can to fire off two find for each search that you want to do.. as I right?

**Comment by nspragg** [comment]
It shouldn't make much difference. Previously, **filesniffer** would accept an instance of **filehound** and execute it's `.find()` method. Once the Promise (array of paths) had fulfilled, it would then start the **filesniffer** search.  

I've run some rudimentary benchmark tests - the difference is negligible.

If you observe a performance degradation in v1, just raise a separate issue and I'll investigate.

**Comment by dvdciri** [comment]
@nspragg I'll keep an eye on the performances thanks!

Also, I don't want to open another issue but it seems like File Hound doesn't work properly on CI, i'm just executing this code below and it returns an empty array of files, while locally the same code returns many different files:
```
const files = await FileHound
    .create()
    .paths(projectRootPath)
    .discard("build")		
    .depth(20)
    .ignoreHiddenDirectories()
    .ignoreHiddenFiles()
    .ext('.java', '.kt')
    .find();
```
 Could you please have a look here https://travis-ci.org/dvdciri/daggraph/jobs/325764383#L477 (no files returned, while locally all tests passes)
I think this was the original problem that i had even on the previous version of file sniffer, i believe that is the reason it wasn't working, but it was hidden inside file sniffer as we were passing the criterias to it. Can you please have a look? 
Thanks

**Comment by nspragg** [comment]
@dvdciri - please raise this issue in FileHound
