### ISSUE TITLE
Folder Recursivity

### ISSUE THREAD

**Issue by eek** [nspragg/filesniffer#7]
I'm having an issue with the filesniffer, it only sniffs in the current document and in neither of the childrens, is there any way to specify that is should also check all children and all children of children?

The only fix I found is changing 
https://github.com/nspragg/filesniffer/blob/master/src/filesniffer.js#L128

and adding `9999` instead of `0`

**Comment by nspragg** [comment]
@eek - thanks for raising this. How are you constructing the instance of filesniffer? You can use pass an instance of **FileHound**, with the required search criteria. In your case try using, `.**depth**`

For example:
https://github.com/nspragg/filesniffer#using-filehound-for-file-searching

For instances created with one or more directories, I'll add a method for enabling a recursive search. 

Hope that helps.

**Comment by nspragg** [comment]
@eek - this is now fixed in master. Should be released as part of a major version within the next few days.

**Comment by nspragg** [comment]
@eek - Fixed in 1.0.3

**Comment by eek** [comment]
Awesome 👍 thanks!
