### ISSUE TITLE
Multiple result per file

### ISSUE THREAD

**Issue by dvdciri** [nspragg/filesniffer#8]
I'm doing a search in files that contains the string target multiple times, and I'm returning the same file path multiple times, as many times as the target string appears.
Is this a bug or is this the expected behaviour? If is expected is there a way to return the file only once if the string appears at least one time?

**Comment by nspragg** [comment]
@dvdciri  - thanks for raising this. It is desired behaviour to emit the filename (fully qualified) and the matching line per match. This is similar to `grep -n someString *.txt` 

It is currently up to the caller of filesniffer to aggregate and process the match events. However, I'm considering adding (optional) support for aggregating results. If you're interested in knowing about this I can keep you updated.

**Comment by dvdciri** [comment]
It would be good if you can add the option as a new functionality and we can keep this open to track the progress so i get notified. Thanks for the reply

**Comment by nspragg** [comment]
Sure - I'll create an issue with all the details.
