### ISSUE TITLE
When combined with FILE_HOUND on CI, (travis) doesn't emit any events

### ISSUE THREAD

**Issue by dvdciri** [nspragg/filesniffer#9]
I noticed that if you run some tests on Travis and specify some search criteria using FILE_HOUND, filesniffer doesn't emit any event, no error, no match and no end.

The same setup that does't work on CI, works locally when i run the tests.

The code is pretty simple:
```
const searchCriteria = FILE_HOUND.create()
    .paths(projectRootPath)
    .discard("build")		
    .depth(20)
    .ignoreHiddenDirectories()
    .ignoreHiddenFiles()
    .ext('.java', '.kt');

  const fileSniffer = FILE_SNIFFER.create(searchCriteria);
// match, end, error
```

If there anything else that i can do to debug and understand what is happening inside filesniffer?

**Comment by nspragg** [comment]
@dvdciri - We have a test for using filehound which is passing on build:
https://github.com/nspragg/filesniffer/blob/master/test/filesniffer.js#L98

Is this still an issue for you?

**Comment by dvdciri** [comment]
@nspragg Yes i still have this issue, i have a test class which is running 6 tests and all of them are passing locally, if i run them on CI they always fail with the error "Promise returned by test never resolved". I've done a lot of tests and investigations to find out what is wrong with the code and i found out that if i remove you library and hardcode some data the code works, if run them with your lib and remove the FILE_HOUND criteria it works.. I'm not quite sure why but the code seems okay.

I'm making an extensive use of your library in my project which is kind of good for me but this error is really driving me crazy, to the point that i had to release a feature with some tests skipped as you can see here, because i couldn't find the reason behind it. 
https://travis-ci.org/dvdciri/daggraph/jobs/321978723.

It would be good if you can have a look at this PR https://github.com/dvdciri/daggraph/pull/27 (just enabled the failing tests) and see if you can verify that is not your lib causing the failure, if is not then i'm happy to close this as invalid. If you don't have time, then let's keep this open while i investigate a bit more.

**Comment by nspragg** [comment]
@dvdciri - thanks for providing this information. I probably won't have time to do a detailed investigation today but I'll have an initial look to see if I can spot anything. 

Will keep you updated.

**Comment by nspragg** [comment]
Incidentally, do you have a link to a failing build report, so I can see the whole of the error message?

**Comment by dvdciri** [comment]
I added the link to the PR in the previous message https://github.com/dvdciri/daggraph/pull/27, it's failing because I've enable the tests.(check the ci failure at the bottom)

**Comment by nspragg** [comment]
Quick suggestion: If the tests pass without the **filehound** instance (criteria), have you tried creating a temporary test that directly asserts the results of the filehound search? 

This would ensure that Filehound results are correct (searching in the expected location etc) and that the promise is resolving. 

May also help check if the test is timing out due to the file search?

**Comment by dvdciri** [comment]
The file hound criteria works correctly as locally all the tests pass and when I manually test it everything is fine. The only problem is the promise not resolving.

I thought about the timeout and I added a timeout of 4 minutes which should be enough, but still doesn't work.. I'll have another look removing filehound

**Comment by nspragg** [comment]
_Potentially_ a related issue: https://github.com/nspragg/filesniffer/issues/10

This is one case where I've found no events are emitted. #10 has been patched.

**Comment by dvdciri** [comment]
Good news, i guess, i upgraded to 0.0.3-alpha.1 and it seems like i have different errors now with more info and the promise is now resolved. Let me have have a deeper look at the errors and see if i now need to fix my code. But that's a good progress. Will keep you updated here, hopefully this will be fixed. Thanks
Check out the new failures here: https://travis-ci.org/dvdciri/daggraph/jobs/323570965

**Comment by dvdciri** [comment]
Yeah, i believe this one can now be closed. If something else comes up i'll update here or raise a new issue, thanks for the support.

**Comment by nspragg** [comment]
@dvdciri  - happy to help out. 

It's probably worth tracking the following issue, as I'm enhancing the api, which may be of use to you: https://github.com/nspragg/filesniffer/issues/11

I'm expecting to make a new major release within the next week.
